const routes = {
  home: "/",
  paymentError: "/payment-error",
  paymentSuccess: "/payment-success",
  login: "/login",
  register: "/register",
  blog: "/blog",
  Info: "/info/:username",
  courseDetail: "/course-detail/:id",
  learning: "/course/learning/:id",
  courses: "/courses",
  setting: "setting",
  createPost: "/create-post",
  savedPost: "/saved-posts",
  myPost: "/my-posts",
  userPost: "/blog/user-posts",
  myCourses: "/my-courses",
  postDetail: "/blog/post-detail/:id",
};
const routesAdmin = {
  dashboard: "/admin/dashboard",
  discount: "/admin/discount",
  discountAdd: "/admin/discount/discount-add",
  discountUpdate: "/admin/discount/discount-update/:id",
  user: "/admin/user",
  userAdd: "/admin/user/user-add",
  userUpdate: "/admin/user/user-update/:id",
  course: "/admin/course",
  courseView: "/admin/course/view/:id",
  courseAdd: "/admin/course/course-add",
  courseUpdate: "/admin/course/course-update/:id",
  courseReceivedAdd: "/admin/course/course-received-add/:id",
  post: "/admin/post",
  postAdd: "/admin/post/post-add",
  postUpdate: "/admin/post/post-update/:id",
  lesson: "/admin/lesson",
  lessonAddUrlVid: "/admin/lesson/lesson-add/url-vid",
  lessonAddNoVid: "/admin/lesson/lesson-add/no-vid",
  lessonAddUploadVid: "/admin/lesson/lesson-add/upload-vid",
  lessonUpdate: "/admin/lesson/lesson-update/:id",
  // lessonCreate: "/admin/lesson/lesson-add",
  category: "/admin/categories",
  categoryAdd: "/admin/categories/category-add",
  categoryUpdate: "/admin/categories/category-update/:id",
  quiz: "/admin/quiz",
  quizAdd: "/admin/quiz/quiz-add",
  quizUpdate: "/admin/quiz/quiz-update/:id",
  quizAnswer: "/admin/quiz/quiz-answer/:id",
  quizAnswerAdd: "/admin/quiz/quiz-answer/add/:id",
  quizAnswerUpdate: "/admin/quiz/quiz-answer/update/:id",
};
export { routes, routesAdmin };
